// imports
import {
  Button,
  Center,
  Container,
  FormControl,
  FormErrorMessage,
  FormLabel,
  Heading,
  Input,
  Text,
  Textarea,
  useToast,
} from "@chakra-ui/react";

import Head from "next/head";

import { BsBorderStyle, BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillFacebook,
  AiFillInstagram,
  AiFillYoutube,
  AiOutlineTwitter,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { SiFiverr } from "react-icons/si";

// images
import Image from "next/image";
import p2 from "../public/p2.png";
import design from "../public/design.png";
import code from "../public/code.png";
import video from "../public/video.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";

import cer1 from "../public/cer1.png";
import cer2 from "../public/cer2.png";
import cer3 from "../public/cer3.png";
import cer4 from "../public/cer4.jpeg";
import cover from "../public/Cover Linkedin.png"
import Typewriter from "typewriter-effect";
//motion
import { color, motion } from "framer-motion";

// hooks
import { useState } from "react";
import { cursorTo } from "readline";
import { sendContactForm } from "../lib/api";
import { ChangeEventHandler } from "react";
import { ChangeEvent } from "react";
import { text } from "stream/consumers";

const initValues = { name: "", email: "", subject: "", message: "" };

const initState = { isLoading: false, error: "", values: initValues };

// applicaiton
export default function Home() {
  // functions
  const [darkmode, setdarkmode] = useState(true);
  const toast = useToast();
  const [state, setState] = useState(initState);
  const [touched, setTouched] = useState({});

  const { values, isLoading, error } = state;
  
       

  const onBlur = ({ target }: ChangeEvent<HTMLInputElement>) =>
    setTouched((prev) => ({ ...prev, [target.name]: true }));

  const handleChange = ({ target }: ChangeEvent<HTMLInputElement>) =>
    setState((prev) => ({
      ...prev,
      values: {
        ...prev.values,
        [target.name]: target.value,
      },
    }));

  const onSubmit = async () => {
    setState((prev) => ({
      ...prev,
      isLoading: true,
    }));
    try {
      await sendContactForm(values);
      setTouched({});
      setState(initState);
      toast({
        title: "Message sent.",
        status: "success",
        duration: 2000,
        position: "top",
      });
    } catch (error) {
      setState((prev) => ({
        ...prev,
        isLoading: false,
        // errorMessage: error.message,
      }));
    }
  };

  return (
    <div className="pb-0 p-0 m-0 bg-black">
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>Portfolio | Saranga Nayanajith</title>
        <meta name="description" content="Generated by create next app" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-poppins bg-no-repeat p-0 bg-black  dark:bg-black">
        <div className="bg-[url('../public/bg7.jpg')] border-none pb-10">
          <section className="min-h-screen px-10 md:px-20 lg:px-40 py-0">
            <nav className="py-10 mb12 flex justify-between">
              <h1 className=" text-xl cursor-pointer dark:text-white">
                ImmersiveX Tech Solutions
              </h1>
              <ul className="flex items-center">
                {/* <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li> */}
                <li>
                  <motion.div
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.9 }}
                    transition={{ duration: 0.1 }}
                  >
                    <a
                      href="#"
                      className="text-white px-4 py-2 rounded-md  bg-blue-700  hover:bg-blue-900"
                    >
                      Resume
                    </a>
                  </motion.div>
                </li>
                <li>
                  <motion.div
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.9 }}
                    transition={{ duration: 0.1 }}
                  >
                    <a
                      href="https://www.fiverr.com/mayomivideo/do-stunning-tik-tok-video-editing-ig-reels-or-story-professionally"
                      className=" mx-5 bg-blue-700 text-white px-4 py-2 boder-none rounded-md hover:bg-blue-900 "
                    >
                      Freelance Service
                    </a>
                  </motion.div>
                </li>
              </ul>
            </nav>

            {/* hero */}
            <div className="text-center p-10 ">
              <h2 className=" text-5xl font-bold text-blue-700 md:text-6xl lg:text-7xl lg:mb-4">
                I'm{" "}
                <span className=" text-blue-300">
                  <Typewriter
                    options={{
                      strings: ["Saranga Nayanajith"],
                      autoStart: true,
                      loop: true,
                    }}
                  />
                </span>
              </h2>
              <h3 className="text-2xl py-4 md:text-3xl dark:text-white">
                <Typewriter
                  options={{
                    strings: [
                      "Full stack web developer",
                      "Mobile app developer",
                      "Freelance Video editor",
                    ],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </h3>
              <p className=" text-sm py-2 text-gray-400 leading-6 md:text-md  max-w-xl mx-auto">
                Hi ! I'm Electrical and information Engineering undergraduate at
                department of Electrical & Information Engineering - University
                of Ruhuna, Sri Lanka. Also freelance Video editor at Fiverr and
                Upwork Platforms.
              </p>
            </div>
            {/* social media */}
            <div className="text-5xl flex justify-center gap-16 text-gray-600">
              <motion.div
                whileHover={{ scale: 1.3 }}
                whileTap={{ scale: 0.9 }}
                transition={{ duration: 0.1 }}
              >
                <a
                  className=" hover:text-blue-700"
                  href="https://facebook.com/Saranga97/"
                >
                  <AiFillFacebook />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.3 }}
                whileTap={{ scale: 0.9 }}
                transition={{ duration: 0.1 }}
              >
                <a
                  className=" hover:text-purple-600"
                  href="https://www.instagram.com/saranga_75/"
                >
                  <AiFillInstagram />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.3 }}
                whileTap={{ scale: 0.9 }}
                transition={{ duration: 0.1 }}
              >
                <a
                  className=" hover:text-red-600"
                  href="https://www.youtube.com/channel/UCc4fzdmJyMq3vXhnFxj0T0w"
                >
                  <AiFillYoutube />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.3 }}
                whileTap={{ scale: 0.9 }}
                transition={{ duration: 0.1 }}
              >
                <a
                  className=" hover:text-blue-500"
                  href="https://www.linkedin.com/in/sarangakarunasundara/"
                >
                  <AiFillLinkedin />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.3 }}
                whileTap={{ scale: 0.9 }}
                transition={{ duration: 0.1 }}
              >
                <a
                  className=" hover:text-white"
                  href="https://github.com/saranga97"
                >
                  <AiFillGithub />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.3 }}
                whileTap={{ scale: 0.9 }}
                transition={{ duration: 0.1 }}
              >
                <a
                  className=" hover:text-green-600"
                  href="https://www.fiverr.com/mayomivideo?up_rollout=true"
                >
                  <SiFiverr />
                </a>
              </motion.div>
            </div>
            {/* profile image */}
            <motion.div
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.7 }}
            >
              <div
                className=" m-auto
           relative bg-gradient-to-b from-blue-200 w-80 p-5
            h-80 mt-20   rounded-full o"
              >
                <Image
                  className=" rounded-full"
                  src={p2}
                  alt="profile"
                  layout="fill"
                  objectFit="cover"
                />
              </div>
            </motion.div>
          </section>
        </div>
        {/* section 2 */}

        <section className="px-10 md:px-20 lg:px-40 py-0">
          <div>
            <h3 className=" text-5xl text-center py-10 font-bold opacity-90 dark:text-white dark:opacity-100 padding-top-10 ">
              Services I offer
            </h3>
            <p className="text-center text-sm py-2 text-gray-400 leading-6">
              As i'm a freelaancer I'm doing video editing as well as graphic
              design. Here are the services I offer.
            </p>
          </div>
          <div className="md:flex lg:flex gap-10 mx-auto">
            <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <div className="text-center shadow-xl p-5 rounded-xl my-10 dark:bg-gradient-to-b from-blue-600 hover:cursor-pointer">
                <Image
                  src={design}
                  width={100}
                  height={100}
                  alt="design"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white ">
                  Front end Web designing
                </h3>
                <p className=" text-sm py-2 text-gray-400 leading-6">
                  I will design front end for your website using modern design
                  tools such as Figma, Adobe XD as well as developing designed
                  website.
                </p>
                <h4 className="py-4 text-blue-600 text-md font-semibold">
                  Design tools I use
                </h4>
                <p className=" text-gray-400 text-sm">Photoshop</p>
                <p className=" text-gray-400 text-sm">Figma</p>
                <p className=" text-gray-400 text-sm">Illustrator</p>
                <p className=" text-gray-400 text-sm">Adobe Xd</p>
              </div>
            </motion.div>
            {/*  */}
            <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-blue-600 hover:cursor-pointer">
                <Image
                  src={code}
                  width={160}
                  height={160}
                  alt="design"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">
                  Website & mobile apps development
                </h3>
                <p className=" text-sm py-2 text-gray-400 leading-6">
                  I will do both Front end and back-end development using any
                  preffered method. Usually I'm going with MERN stack or .NET
                  framework
                </p>
                <h4 className="py-4 text-blue-600 text-md font-semibold">
                  Modern tools I use :
                </h4>
                <p className=" text-gray-400 text-sm">NodeJS/.NET</p>
                <p className=" text-gray-400 text-sm">React-Express-NextJS</p>
                <p className=" text-gray-400 text-sm">Tailwind CSS</p>
                <p className=" text-gray-400 text-sm">MongoDb/SQL</p>
              </div>
            </motion.div>
            {/*  */}
            <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-blue-700 hover:cursor-pointer">
                <Image
                  src={video}
                  width={100}
                  height={100}
                  alt="design"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">
                  Video editing and animation
                </h3>
                <p className=" text-sm py-2 text-gray-400 leading-6">
                  I will do any kind of video editing and animation services for
                  afforadable price. You can see sample videos I created from
                  portfolio below.
                </p>
                <h4 className="py-4 text-blue-600 text-md font-semibold">
                  Design tools I use
                </h4>
                <p className=" text-gray-400 text-sm">Adobe Premiere Pro</p>
                <p className=" text-gray-400 text-sm">Adobe After effects</p>
                <p className=" text-gray-400 text-sm">Final Cut Pro</p>
                <p className=" text-gray-400 text-sm">Davinci Resolve</p>
              </div>
            </motion.div>
          </div>
        </section>
        <section className="px-10 md:px-20 lg:px-40 py-0">
          <div className="pb-20">
            <h3 className=" text-5xl text-center py-10 font-bold opacity-60 dark:text-white dark:opacity-100">
              Certificates
            </h3>
            <div className="flex flex-col gap-10 lg:flex-wrap lg:flex-row">
              <div className="basis-1/5 flex-1">
              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                <Image
                  src={cer1}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
                </motion.div>
              </div>
              
              <div className="basis-1/5 flex-1">
              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                <Image
                  src={cer2}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
                </motion.div>
                
              </div>
              <div className="basis-1/5 flex-1">
              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                <Image
                  src={cer3}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
                </motion.div>
                
              </div>
              <div className="basis-1/5 flex-1">
              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                <Image
                  src={cer4}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
                </motion.div>
                
              </div>
            </div>
          </div>
        </section>

        {/*                             PORTFOLIO                    */}

        <section className="px-10 md:px-20 lg:px-40 py-0">
          <div>
            <h3 className=" text-5xl text-center pt-15 font-bold opacity-60 dark:text-white dark:opacity-100">
              Portfolio
            </h3>
            <p className="text-center text-sm py-10 text-gray-400 leading-6">
              Here are some collection of my projects and client works that
              demonstrates my skills, experience, and achievements. It serves as
              a showcase of their my work and abilities.
            </p>
          </div>
          {/* images */}
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={web1}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={web2}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={web3}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={web4}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
              </motion.div>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={web2}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={web1}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full"
                  layout="responsive"
                />
              </motion.div>
            </div> */}
          </div>
        </section>

        <section className="px-10 md:px-20 lg:px-40 pt-20">
          <div>
            <h3 className="text-5xl text-center pt-15 font-bold opacity-60 dark:text-white dark:opacity-100">ImmersiveX Tech Solutions</h3>
            <p className="text-center text-sm py-10 text-gray-400 leading-6"> Welcome to our new Freelancing Start up!</p>
          </div>
          <div className="lg:px-60 sm:px:5 md:px-5">
          <Image
                  src={cover}
                  alt="web images"
                  className="rounded-lg object-cover w-full h-full hover:shadow-xl shadow-white"
                  layout="responsive"
                />
          </div>
        </section>

        <section>
          <div>


          </div>



        </section>

      <section className="px-20 md:px-10 lg:px-10 pt-20 pb-10 items-center ">
        <div className="">
      <div className="items-center">
            <h3 className="text-5xl text-center pt-15 font-bold opacity-60 dark:text-white dark:opacity-100">Contact Me</h3>
            <p className="text-center text-sm py-5 text-gray-400 leading-6"> You can get in touch with me via putting an E-mail.</p>
          </div>
      <Container className="items-center" maxW="700px" mt={10}>
      {error && (
        <Text color="red.300" my={4} fontSize="xl">
          {error}
        </Text>
      )}
 <FormControl isRequired  mb={5}>
  {/* isInvalid={touched.name && !values.name} */}
        <FormLabel color={"White"}>Name</FormLabel>
        <Input
          type="text"
          name="name"
          errorBorderColor="red.300"
          value={values.name}
          onChange={handleChange}
          onBlur={onBlur}
        />
        <FormErrorMessage>Required</FormErrorMessage>
      </FormControl>

      <FormControl isRequired  mb={5}>                     
       {/* //isInvalid={touched.email && !values.email} */}
        <FormLabel color={"White"}>Email</FormLabel>
        <Input
          type="email"
          name="email"
          errorBorderColor="red.300"
          value={values.email}
          onChange={handleChange}
          onBlur={onBlur}
        />
        <FormErrorMessage>Required</FormErrorMessage>
      </FormControl>

      <FormControl
        mb={5}
        isRequired
        // isInvalid={touched.subject && !values.subject}
      >
        <FormLabel color={"White"}>Subject</FormLabel>
        <Input
          type="text"
          name="subject"
          errorBorderColor="red.300"
          value={values.subject}
          onChange={handleChange}
          onBlur={onBlur}
        />
        <FormErrorMessage>Required</FormErrorMessage>
      </FormControl>

      <FormControl
        isRequired
        isInvalid={!values.message} //"touched.message && "
        mb={5}
      >
        <FormLabel color={"White"}>Message</FormLabel>
        <Textarea
          
          name="message"
          rows={5}
          errorBorderColor="red.300"
          value={values.message}
          // onChange={handleChange}
          // onBlur={onBlur}
        />
        <FormErrorMessage>Required</FormErrorMessage>
      </FormControl>
      <Center>
      <Button className=" text-center self-center items-center justify-center"
        variant={"outline"}
        colorScheme="blue"
        isLoading={isLoading}
        disabled={
          !values.name || !values.email || !values.subject || !values.message
        }
        onClick={onSubmit}
      >
        Submit
      </Button>
      </Center>
    </Container>
    </div>



        </section>


        {/*                                    FOOTER                                       */}
        <footer className="px-10 md:px-20 lg:px-40 border-t-2 border-black  text-sm opacity-70 flex flex-col gap-5 items-center justify-center py-10 mt-20 lg:flex-row lg:items-center bg-blue-800 text-white">
          <div>
            <h3 className=" text-xl mb-2">Contact me for more details</h3>
            <p className=" opacity-40">
              {" "}
              Here are some summary of my works and projects. So If you wanr
              more details you can reach me using these social media links or
              contact via direct E-mail or Dial +9471-196-7138.
            </p>
          </div>
          <div>
            <div className="text-5xl flex justify-center ml-10 gap-16 text-white-400">
              <a href="https://facebook.com/Saranga97/">
                <AiFillFacebook />
              </a>
              <a href="https://www.instagram.com/saranga_75/">
                <AiFillInstagram />
              </a>
              <a href="https://www.youtube.com/channel/UCc4fzdmJyMq3vXhnFxj0T0w">
                <AiFillYoutube />
              </a>
              <a href="https://www.linkedin.com/in/sarangakarunasundara/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/saranga97">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </footer>
      </main>
    </div>
    </div>
  );
}
